def generate_report(user, url, vulnerabilities, tech_stack_info=None, cve_findings=None):
    from datetime import datetime

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with open("report.html", "w", encoding="utf-8") as report:
        report.write(f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Advanced Fuzzer Report</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
            <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
            <style>
                body {{
                    background-color: #f5f6fa;
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    line-height: 1.6;
                }}
                .badge-high {{ background-color: #e74c3c; }}
                .badge-medium {{ background-color: #f1c40f; color: #000; }}
                .badge-low {{ background-color: #2ecc71; }}
                .dark-mode {{
                    background-color: #1e1e2f !important;
                    color: #f5f6fa !important;
                }}
                .dark-mode .card {{
                    background-color: #2a2a40 !important;
                    color: #f5f6fa !important;
                    border-color: #444;
                }}
                .dark-mode .table thead {{
                    background-color: #333 !important;
                    color: #f5f6fa !important;
                }}
                .dark-mode .list-group-item {{
                    background-color: #2a2a40;
                    color: #f5f6fa;
                }}
                .table-hover tbody tr:hover {{
                    background-color: #dff9fb;
                }}
                .dark-mode .table-hover tbody tr:hover {{
                    background-color: #44475a;
                }}
                .section-toggle {{
                    cursor: pointer;
                    user-select: none;
                }}
                .section-header {{
                    background-color: #3498db;
                    color: white;
                    padding: 10px 20px;
                    border-radius: 6px;
                    margin-bottom: 10px;
                }}
                .card {{
                    border: 1px solid #dee2e6;
                    border-radius: 0.5rem;
                    margin-bottom: 1rem;
                }}
                .card-body {{
                    padding: 1rem;
                }}
                .vuln-title {{
                    font-weight: bold;
                    font-size: 1.25rem;
                    color: #e67e22;
                }}
                code {{
                    background-color: #f2f2f2;
                    padding: 2px 6px;
                    border-radius: 5px;
                    font-size: 0.95rem;
                    color: #c0392b;
                }}
            </style>
        </head>
        <body class="p-4">
            <div class="container">
                <div class="d-flex justify-content-between align-items-center">
                    <h1 class="mb-4"><i class="fas fa-shield-alt"></i> Advanced Fuzzer Report</h1>
                    <button class="btn btn-dark" onclick="toggleDarkMode()">🌗 Dark Mode</button>
                </div>
                <div class="mb-3">
                    <p><strong>🔗 URL Tested:</strong> {url}</p>
                    <p><strong>👤 Generated by:</strong> {user} &nbsp;&nbsp; <strong>📅 Date:</strong> {now}</p>
                </div>
                <input type="text" id="searchInput" class="form-control my-3" placeholder="Search payloads...">

                <h2 class=\"mt-4 section-header\">\ud83d\udd27 Technology Stack Detected</h2>
                <div class=\"card mb-4\">
                    <div class=\"card-body\">
                        """ + "{tech_stack_section}" + """
                    </div>
                </div>

                <h2 class=\"mt-4 section-header\">\ud83d\udea8 CVE Threat Intelligence</h2>
                <div class=\"card mb-4\">
                    <div class=\"card-body\">
                        """ + "{cve_section}" + """
                    </div>
                </div>

                <h2 class=\"mt-4 section-header\">\ud83d\udee1\ufe0f Vulnerabilities Found</h2>
        """)

        # Generate tech stack section
        tech_stack_section = ""
        if tech_stack_info:
            tech_stack_section = "<h5><i class='fas fa-cogs'></i> Detected Technologies</h5><div class='row'>"
            for tech, details in tech_stack_info.items():
                versions = details.get('versions', ['Unknown version'])
                categories = details.get('categories', ['Unknown category'])
                version_str = ', '.join(versions) if versions else 'Unknown version'
                category_str = ', '.join(categories) if categories else 'Unknown category'
                tech_stack_section += f"""
                <div class="col-md-4 mb-3">
                    <div class="card border-primary">
                        <div class="card-body">
                            <h6 class="card-title text-primary"><i class="fas fa-puzzle-piece"></i> {tech}</h6>
                            <p class="card-text small"><strong>Version:</strong> {version_str}</p>
                            <p class="card-text small"><strong>Category:</strong> {category_str}</p>
                        </div>
                    </div>
                </div>
                """
            tech_stack_section += "</div>"
        else:
            tech_stack_section = "<p class='text-muted'><i class='fas fa-info-circle'></i> No technology stack information available.</p>"

        # Generate CVE section
        cve_section = ""
        if cve_findings:
            cve_section = "<h5><i class='fas fa-exclamation-triangle'></i> Known CVEs for Detected Technologies</h5>"
            total_cves = sum(len(cves) for cves in cve_findings.values())
            if total_cves > 0:
                cve_section += f"<div class='alert alert-warning'><i class='fas fa-shield-alt'></i> Found <strong>{total_cves}</strong> potential CVEs across detected technologies.</div>"
                for tech, cves in cve_findings.items():
                    if cves:
                        cve_section += f"<div class='mb-3'><h6 class='text-danger'><i class='fas fa-server'></i> {tech}</h6><ul class='list-group'>"
                        for cve in cves[:3]:  # Show top 3 CVEs per technology
                            cve_section += f"""
                            <li class="list-group-item">
                                <div class="d-flex justify-content-between align-items-start">
                                    <div>
                                        <strong class="text-danger">{cve.get('id', 'Unknown')}</strong>
                                        <p class="mb-1 small">{cve.get('summary', 'No description available')[:200]}...</p>
                                        <small><a href="{cve.get('references', [''])[0] if cve.get('references') else '#'}" target="_blank" class="text-decoration-none">View Details</a></small>
                                    </div>
                                </div>
                            </li>
                            """
                        if len(cves) > 3:
                            cve_section += f"<li class='list-group-item text-muted'><i class='fas fa-ellipsis-h'></i> ...and {len(cves) - 3} more CVEs</li>"
                        cve_section += "</ul></div>"
            else:
                cve_section += "<div class='alert alert-success'><i class='fas fa-check-circle'></i> No known CVEs found for detected technologies.</div>"
        else:
            cve_section = "<p class='text-muted'><i class='fas fa-info-circle'></i> CVE analysis not available.</p>"

        categories = {
            "SQL Injection": [],
            "Cross-Site Scripting (XSS)": [],
            "Command Injection": [],
            "Directory Traversal": [],
            "Broken Authentication": [],
            "Security Misconfiguration": [],
            "Sensitive Data Exposure": [],
            "Insecure File Upload": [],
            "Cross-Site Request Forgery (CSRF)": [],
            "IDOR": [],
            "Brute Force / Multiple Login Attempts": []
        }

        for vuln in vulnerabilities:
            if vuln["type"] in categories:
                categories[vuln["type"]].append(vuln)
            else:
                categories["Security Misconfiguration"].append(vuln)

        vuln_index = 0
        for category, vulns in categories.items():
            if vulns:
                report.write(f"""
                <div class="card">
                    <div class="card-header section-toggle" onclick="toggleSection('section{vuln_index}')">
                        <span class="vuln-title"><i class="fas fa-exclamation-circle"></i> {category}</span>
                    </div>
                    <div class="card-body" id="section{vuln_index}">
                        <table class="table table-hover table-bordered table-striped">
                            <thead class="table-dark">
                                <tr>
                                    <th>Payload</th>
                                    <th>Recommendation</th>
                                    <th>Severity</th>
                                </tr>
                            </thead>
                            <tbody>
                """)
                for vuln in vulns:
                    severity = vuln.get("severity", "Medium").capitalize()
                    badge_class = {
                        "High": "badge-high",
                        "Medium": "badge-medium",
                        "Low": "badge-low"
                    }.get(severity, "badge-medium")
                    report.write(f"""
                        <tr>
                            <td><code>{vuln['payload']}</code></td>
                            <td>{vuln['recommendation']}</td>
                            <td><span class="badge {badge_class}">{severity}</span></td>
                        </tr>
                    """)
                report.write("""
                            </tbody>
                        </table>
                    </div>
                </div>
                """)
                vuln_index += 1

        if not vulnerabilities:
            report.write("<div class='alert alert-success'>No vulnerabilities found!</div>")

        report.write("""
            <h2 class="mt-5 section-header">General Security Solutions</h2>
            <ul class="list-group mb-5">
                <li class="list-group-item"><b>SQL Injection:</b> Use parameterized queries and ORM frameworks.</li>
                <li class="list-group-item"><b>XSS:</b> Sanitize input and use Content Security Policy (CSP).</li>
                <li class="list-group-item"><b>Command Injection:</b> Avoid shell commands, validate input strictly.</li>
                <li class="list-group-item"><b>Directory Traversal:</b> Use secure APIs and validate file paths.</li>
                <li class="list-group-item"><b>CSRF:</b> Use CSRF tokens and SameSite cookie attributes.</li>
                <li class="list-group-item"><b>IDOR:</b> Enforce object-level authorization.</li>
                <li class="list-group-item">Enable a Web Application Firewall (WAF).</li>
                <li class="list-group-item">Keep frameworks and libraries up-to-date.</li>
            </ul>
        </div>

        <script>
            function toggleDarkMode() {{
                document.body.classList.toggle('dark-mode');
            }}

            function toggleSection(id) {{
                const el = document.getElementById(id);
                el.style.display = el.style.display === "none" ? "block" : "none";
            }}

            document.getElementById('searchInput').addEventListener('input', function () {{
                let filter = this.value.toLowerCase();
                document.querySelectorAll("tbody tr").forEach(row => {{
                    const text = row.textContent.toLowerCase();
                    row.style.display = text.includes(filter) ? '' : 'none';
                }});
            }});
        </script>

        </body>
        </html>
        """)
